/* TASKS */
export const STATUS_REQUEST = "STATUS_REQUEST"
export const UPDATE_STATUS_RESET = "UPDATE_STATUS_RESET"
export const UPDATE_STATUS_SUCCESS = "UPDATE_STATUS_SUCCESS"
export const GET_COMMON_FAIL = "GET_COMMON_FAIL"
